# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import avod.protos.model_pb2 as model__pb2
import avod.protos.train_pb2 as train__pb2
import avod.protos.eval_pb2 as eval__pb2
import avod.protos.kitti_dataset_pb2 as kitti__dataset__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pipeline.proto',
  package='avod.protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0epipeline.proto\x12\x0b\x61vod.protos\x1a\x0bmodel.proto\x1a\x0btrain.proto\x1a\neval.proto\x1a\x13kitti_dataset.proto\"\xde\x01\n\x15NetworkPipelineConfig\x12.\n\x0cmodel_config\x18\x01 \x01(\x0b\x32\x18.avod.protos.ModelConfig\x12.\n\x0ctrain_config\x18\x02 \x01(\x0b\x32\x18.avod.protos.TrainConfig\x12,\n\x0b\x65val_config\x18\x03 \x01(\x0b\x32\x17.avod.protos.EvalConfig\x12\x37\n\x0e\x64\x61taset_config\x18\x04 \x01(\x0b\x32\x1f.avod.protos.KittiDatasetConfig'
  ,
  dependencies=[model__pb2.DESCRIPTOR,train__pb2.DESCRIPTOR,eval__pb2.DESCRIPTOR,kitti__dataset__pb2.DESCRIPTOR,])




_NETWORKPIPELINECONFIG = _descriptor.Descriptor(
  name='NetworkPipelineConfig',
  full_name='avod.protos.NetworkPipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_config', full_name='avod.protos.NetworkPipelineConfig.model_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='avod.protos.NetworkPipelineConfig.train_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval_config', full_name='avod.protos.NetworkPipelineConfig.eval_config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset_config', full_name='avod.protos.NetworkPipelineConfig.dataset_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=313,
)

_NETWORKPIPELINECONFIG.fields_by_name['model_config'].message_type = model__pb2._MODELCONFIG
_NETWORKPIPELINECONFIG.fields_by_name['train_config'].message_type = train__pb2._TRAINCONFIG
_NETWORKPIPELINECONFIG.fields_by_name['eval_config'].message_type = eval__pb2._EVALCONFIG
_NETWORKPIPELINECONFIG.fields_by_name['dataset_config'].message_type = kitti__dataset__pb2._KITTIDATASETCONFIG
DESCRIPTOR.message_types_by_name['NetworkPipelineConfig'] = _NETWORKPIPELINECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkPipelineConfig = _reflection.GeneratedProtocolMessageType('NetworkPipelineConfig', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKPIPELINECONFIG,
  '__module__' : 'pipeline_pb2'
  # @@protoc_insertion_point(class_scope:avod.protos.NetworkPipelineConfig)
  })
_sym_db.RegisterMessage(NetworkPipelineConfig)


# @@protoc_insertion_point(module_scope)
